### PR TITLE
Fixed some typos and usage example

### PR DESCRIPTION
**Pull request by pawlos**

### CODE REVIEW

**Review by hexfati — APPROVED** [review]
thanks @pawlos . I hope this project is useful

**Comment by pawlos** [comment]
I was a bit surprised not to find source code but just binaries. Are there any plans to release as a source code?

**Comment by hexfati** [comment]
I plan to release it shortly, even if it is a really trivial code

**Comment by pawlos** [comment]
Yes, I know it's simple. Had to check if the code does what it says it does before executing ;)

**Pull request merged**
